// Copyright 2026 The Helium Authors. GPL-3.0; see LICENSE.
// DOM-free workspace model shared by the native WebUI and its development preview.
export const COLORS = ['#f6a3a9', '#b7a0d8', '#9bbec4', '#aebf9d', '#d9b38d', '#b4b9c9'];
export const uid = () => crypto.randomUUID();
const text = (value, fallback = '') => typeof value === 'string' ? value.slice(0, 2048) : fallback;
export function safeURL(value) {
  try {
    const url = new URL(value);
    return ['https:', 'http:', 'chrome:', 'helium:', 'about:', 'file:'].includes(url.protocol) ? url.href : '';
  } catch { return ''; }
}
export function createState() {
  return {version: 1, activeSpace: 'personal', spaces: [
    {id: 'personal', name: 'Personal', color: COLORS[0], icon: '✦'},
  ], nodes: [], bindings: {}, lastActive: {}};
}
export function restoreState(input) {
  if (!input || input.version !== 1 || !Array.isArray(input.spaces)) return createState();
  const state = createState();
  const seen = new Set();
  state.spaces = input.spaces.slice(0, 32).filter(s => s && typeof s.id === 'string' && !seen.has(s.id) && seen.add(s.id)).map(s => ({
    id: text(s.id), name: text(s.name, 'Untitled').slice(0, 80),
    color: /^#[0-9a-f]{6}$/i.test(s.color) ? s.color : COLORS[0], icon: text(s.icon, '✦').slice(0, 8),
  }));
  if (!state.spaces.length) return createState();
  state.activeSpace = state.spaces.some(s => s.id === input.activeSpace) ? input.activeSpace : state.spaces[0].id;
  const spaces = new Set(state.spaces.map(s => s.id));
  seen.clear();
  state.nodes = (Array.isArray(input.nodes) ? input.nodes : []).slice(0, 5000).filter(n =>
    n && typeof n.id === 'string' && ['folder', 'tab'].includes(n.type) && spaces.has(n.space) &&
    !seen.has(n.id) && seen.add(n.id)).map(n => ({
      id: text(n.id), type: n.type, space: n.space, parent: text(n.parent) || null,
      name: text(n.name, 'Untitled'), url: safeURL(n.url), pinned: n.type === 'folder' || !!n.pinned,
      favorite: n.type === 'tab' && !!n.favorite, collapsed: !!n.collapsed,
    }));
  for (const n of state.nodes) {
    if (!validParent(state, n.id, n.parent, n.space)) n.parent = null;
    if (n.favorite) { n.parent = null; n.pinned = true; }
  }
  // Keys are generated by the native host: a window session plus tab session ID.
  // Keep other windows' bindings so saving one window never reassigns another's tabs.
  for (const [key, value] of Object.entries(input.bindings || {}).slice(0, 10000)) {
    if (/^\d+:\d+$/.test(key) && typeof value === 'string' && state.nodes.some(n => n.id === value && n.type === 'tab')) state.bindings[key] = value;
  }
  for (const [key, value] of Object.entries(input.lastActive || {})) {
    if (spaces.has(key) && typeof value === 'string') state.lastActive[key] = value;
  }
  return state;
}
export const nodeById = (state, id) => state.nodes.find(n => n.id === id);
export function validParent(state, id, parent, space) {
  const visited = new Set([id]);
  while (parent) {
    if (visited.has(parent)) return false;
    visited.add(parent);
    const folder = nodeById(state, parent);
    if (!folder || folder.type !== 'folder' || folder.space !== space) return false;
    parent = folder.parent;
  }
  return true;
}
export function descendants(state, id) {
  const found = new Set([id]);
  let changed = true;
  while (changed) {
    changed = false;
    for (const n of state.nodes) if (found.has(n.parent) && !found.has(n.id)) { found.add(n.id); changed = true; }
  }
  return found;
}
export function addSpace(state, name, color = COLORS[state.spaces.length % COLORS.length]) {
  if (state.spaces.length >= 32) return null;
  const space = {id: uid(), name: name.trim().slice(0, 80) || 'Untitled', color, icon: ['✦', '◈', '❋', '☀', '◒'][state.spaces.length % 5]};
  state.spaces.push(space);
  return space;
}
export function deleteSpace(state, id) {
  if (state.spaces.length < 2 || !state.spaces.some(s => s.id === id)) return false;
  const destination = state.spaces.find(s => s.id !== id).id;
  // Preserve tabs and folders when deleting a space.
  for (const n of state.nodes) if (n.space === id) n.space = destination;
  state.spaces = state.spaces.filter(s => s.id !== id);
  if (state.activeSpace === id) state.activeSpace = destination;
  delete state.lastActive[id];
  return true;
}
export function addFolder(state, name, parent = null) {
  const n = {id: uid(), type: 'folder', name: name.trim() || 'New Folder', space: state.activeSpace, parent, pinned: true, collapsed: false};
  if (!validParent(state, n.id, parent, n.space)) return null;
  state.nodes.push(n);
  return n;
}
export function moveNode(state, id, {space = state.activeSpace, parent = null, before = null, pinned = true, favorite = false} = {}) {
  const n = nodeById(state, id);
  if (!n || !state.spaces.some(s => s.id === space) || !validParent(state, id, parent, space)) return false;
  const moving = descendants(state, id);
  if (moving.has(before)) return false;
  for (const child of state.nodes) if (moving.has(child.id)) child.space = space;
  Object.assign(n, {parent: favorite ? null : parent, pinned: n.type === 'folder' || pinned || !!parent || favorite, favorite: n.type === 'tab' && favorite});
  state.nodes = state.nodes.filter(item => item !== n);
  const index = before ? state.nodes.findIndex(item => item.id === before) : -1;
  state.nodes.splice(index < 0 ? state.nodes.length : index, 0, n);
  return true;
}
export function removeNode(state, id) {
  const removed = descendants(state, id);
  state.nodes = state.nodes.filter(n => !removed.has(n.id));
  for (const [key, value] of Object.entries(state.bindings)) if (removed.has(value)) delete state.bindings[key];
}
export function reconcile(state, snapshot) {
  const prefix = `${snapshot.windowId}:`;
  const liveKeys = new Set(snapshot.tabs.map(t => prefix + t.id));
  for (const [key, id] of Object.entries(state.bindings)) {
    if (key.startsWith(prefix) && !liveKeys.has(key)) {
      delete state.bindings[key];
      const n = nodeById(state, id);
      if (n && !n.pinned && !n.favorite && !Object.values(state.bindings).includes(id)) removeNode(state, id);
    }
  }
  for (const tab of snapshot.tabs) {
    const key = prefix + tab.id;
    let n = nodeById(state, tab.nodeId) || nodeById(state, state.bindings[key]);
    if (n) state.bindings[key] = n.id;
    if (!n) {
      // Consume each matching dormant entry once, preserving duplicate URLs.
      n = state.nodes.find(item => item.type === 'tab' && item.url === tab.url &&
        !Object.entries(state.bindings).some(([k, v]) => k.startsWith(prefix) && v === item.id));
      if (!n) {
        n = {id: uid(), type: 'tab', name: tab.title || 'New Tab', url: safeURL(tab.url), space: state.activeSpace, parent: null, pinned: !!tab.pinned, favorite: !!tab.pinned};
        state.nodes.push(n);
      }
      state.bindings[key] = n.id;
    }
    // Pinned tabs keep their chosen title and home URL across navigation.
    if (!n.pinned) { n.name = tab.title || 'New Tab'; n.url = safeURL(tab.url); }
    if (tab.active) {
      if (!n.favorite) state.activeSpace = n.space;
      state.lastActive[state.activeSpace] = n.id;
    }
  }
  return state;
}
export function liveTab(state, snapshot, id) {
  return snapshot.tabs.find(t => state.bindings[`${snapshot.windowId}:${t.id}`] === id);
}
export function visibleNodes(state, parent = null, pinned = true) {
  return state.nodes.filter(n => n.space === state.activeSpace && n.parent === parent && !!n.pinned === pinned && !n.favorite);
}
